package com.example.domain;

public enum GenreEnum {
	
	COMMEDY, HORROR, ROMANCE, THRILLER, DRAMA, CRIME, ACTION, WESTERN, MISTERY, SCI_FI,
	FANTASY, HISTORY, DOCUMENTARY, ADVENTURE, BIOGRAPHY, MUSICAL, SUPERHERO, WAR

}
